deploy_env: staging
env_monitoring_id: staging
users:
  - dimagi
  - dimagi-qa
  - dimagi-interns
  - g2
  - fissionlabs
  - fission-warehouse
secrets_backend: aws-secrets

shared_mount_opts: "_netdev,nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2,noresvport"
