---

- name: EFS Mount Target
  hosts: shared_efs_client_host
  become: yes
  vars:
      shared_dir_user: nobody
      shared_dir_group: "{{ shared_dir_gid }}"
      shared_dir_groupname: nfs
      shared_dir_name: "{{ efs_shared_mount_dir }}"
      shared_mount_dir: "/mnt/{{ efs_shared_mount_dir }}"
      shared_mount_address: "{{ efs_shared_mount_endpoint }}"
  tasks:
    - import_tasks: roles/shared_dir/tasks/install.yml
    - import_tasks: roles/shared_dir/tasks/setup_client.yml
  tags:
    - efs_mount_shared_dir
    - nfs