---

- name: EFS Mount Target
  hosts: shared_efs_client_host
  become: yes
  vars:
      shared_mount_opts: "_netdev,nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2,noresvport"
      shared_mount_address: "{{ efs_staging_mount|default(None) }}"
      shared_dir_user: nobody
      shared_dir_group: "{{ shared_dir_gid }}"
      shared_dir_groupname: nfs
  vars_files:
    - group_vars/all.yml
  tasks:
    - import_tasks: roles/shared_dir/tasks/install.yml
    - import_tasks: roles/shared_dir/tasks/setup_client.yml
